package com.pallas.jclcreator.errors;

import java.time.LocalDateTime;

import javax.naming.InvalidNameException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.fasterxml.jackson.databind.exc.InvalidFormatException;
import com.pallas.jcl.creator.job.exceptions.DuplicateJclElementException;
import com.pallas.jcl.creator.job.exceptions.InvalidParameterException;
import com.pallas.jcl.creator.job.exceptions.JclElementNotFoundException;
import com.pallas.jclcreator.builders.EventBuilder;
import com.pallas.jclcreator.service.EventServiceDefinition;

public abstract class ErrorHandler {
	  
    @Autowired
    private EventServiceDefinition service;
		
    @ExceptionHandler({ 
	  InvalidNameException.class, 
	  InvalidParameterException.class, 
	  DuplicateJclElementException.class,
	  InvalidFormatException.class,
	  NullPointerException.class,
	  InvalidFormatException.class,
	  JclElementNotFoundException.class})
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public String handleException(Exception ex) {
        this.service.logEvent(new EventBuilder()
		.setDate(LocalDateTime.now())
		.setDescription("Error generated by ".concat(ex.getClass().toString()).concat(": ").concat(ex.getMessage()))
		.setTitle(ex.getMessage()).build());
        return ex.getMessage();
    }	  	  
}
